### ISSUE TITLE
EUTL certificates are not decoding

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/tl-create#2]
Blobs encoded as "BEGIN/END CERTIFICATE" do not decode with:

```
openssl x509 -in test.cer -text -inform PEM
```

They should.

Not sure were grabbing the right things out of the EUTL.

**Comment by as-if-ur** [comment]
Solved. we were taking the right things. But i think openssl expect 64 characters in each line. we were showing all info in one line/ that's why openssl couldn't decode. Now certificate info is showing 64 characters in one line.
