### ISSUE TITLE
Need to download certdata.txt

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/tl-create#22]
Looks like we are not using:

```var mozillaUrl = "http://mxr.mozilla.org/mozilla/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1";```

To download the certdata.txt and are instead relying on the one in the data directory only:
```
var mozillaLocalUrl = "/../data/certdata.txt";
```

**Comment by as-if-ur** [comment]
solved
