### ISSUE TITLE
Update README to list all Microsoft supported usages

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/tl-create#40]
We list the Mozilla supported usages but not the Microsoft ones.

**Comment by rmhrisk** [comment]
I think it would be these:
```
  SERVER_AUTH
  CLIENT_AUTH
  CODE_SIGNING
  EMAIL_PROTECTION
  IPSEC_END_SYSTEM
  IPSEC_TUNNEL
  IPSEC_USER
  TIME_STAMPING
```

**Comment by fotisl** [comment]
This is the common subset of the Mozilla and Microsoft supported usages. Microsoft has some additional ones that do not exist in Mozilla. Should these be added?

**Comment by rmhrisk** [comment]
Would be great if they could be.
