### ISSUE TITLE
Only take EUTL entries where "Service Status"="TrustedList/Svcstatus/accredited"

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/tl-create#5]
We should only take entries where "Service Status"="TrustedList/Svcstatus/accredited"

**Comment by as-if-ur** [comment]
is it related to CA/QA the other issue? should we take those have CA/QA and this ServiceStatus or take if one matches?

**Comment by rmhrisk** [comment]
This would be in addition to the CA check.

 In other  words we should only take accredited certificate authorities.

**Comment by as-if-ur** [comment]
solved
