### ISSUE TITLE
Only take EUTL entries where they are CAs

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/tl-create#6]
It seems the list can have more than just CA certificates, need to filter to those that are just CA certificates.

**Comment by rmhrisk** [comment]
CAs have a ServiceTypeIdentifier of:
- http://uri.etsi.org/TrstSvc/Svctype/NationalRootCA-QC 
- http://uri.etsi.org/TrstSvc/Svctype/CA/PKC/
- http://uri.etsi.org/TrstSvc/Svctype/CA/QC

**Comment by as-if-ur** [comment]
Solved
