### ISSUE TITLE
Problem downloading cisco trust store

### ISSUE THREAD

**Issue by fotisl** [PeculiarVentures/tl-create#61]
When trying to download the cisco trust store I get the following error:

> Parsing started: 2017:11:02:19:34:37
> Trust Lists: Cisco - union
> Output format: PEM
> Error: TypeError: engine.subtle.getAlgorithmByOID is not a function
>     at getAlgorithmByOID (/XXX/tl-create/node_modules/pkijs/build/common.js:271:23)
>     at /XXX/tl-create/node_modules/pkijs/build/SignedData.js:766:65
>     at process._tickCallback (internal/process/next_tick.js:109:7)
>     at Module.runMain (module.js:606:11)
>     at run (bootstrap_node.js:383:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:496:3

I am not sure if this should be filed here, or at the PKI.js repo.

**Comment by YuryStrozhevsky** [comment]
@fotisl You should put specific version for PKIjs in package.json:
```
pkijs: "2.0.67"
```

There are big changes in newest versions of PKIjs and your code is not aligned with it (yet, at least).

**Comment by fotisl** [comment]
Hello,
I think that I have found the root cause of the problem. At pki.js commit 169029a0041c2f85c59f95491d2f22767631c7e4, getAlgorithmByOID() was changed at common.js to use engine.subtle.getAlgorithmByOID(algorithm). However, node-webcrypto-ossl does not implement getAlgorithmByOID. Using an older version such as 2.0.67 should solve this, but shouldn't getAlgorithmByOID be implemented?

**Comment by microshine** [comment]
@fotisl Try to use new PKIjs API
```js
const {setEngine, CryptoEngine} = require("pkijs");
const CryptoOSSL = require("node-webcrypto-ossl");
const crypto = new CryptoOSSL;

setEngine("OpenSSL", crypto, new CryptoEngine({ name: "", crypto, subtle: crypto.subtle }));
```

**Comment by fotisl** [comment]
It works as is (after the latest xmldsigjs fix). Thanks. I just didn't know if there is another problem in pkijs that you didn't know.

**Comment by microshine** [comment]
I applied the newest PKIjs API in the last xmldsigjs
