### ISSUE TITLE
Errors during fetching lists

### ISSUE THREAD

**Issue by YuryStrozhevsky** [PeculiarVentures/tl-create#65]
![untitled](https://user-images.githubusercontent.com/6128446/34865520-0f3c383e-f78a-11e7-91b0-b797b6af8197.jpg)

**Comment by rmhrisk** [comment]
@fotisl any ideas

**Comment by fotisl** [comment]
Unfortunately one TSL is served by a webserver that sends the wrong certificate chain, and thus the connection fails. I have contacted the administrator and they should fix it.
For the Microsoft trust list you must have the 'expand' command to extract the stl from the cab file. Can you try running it manually?

**Comment by YuryStrozhevsky** [comment]
@fotisl What exactly I need to write in console for MS list?

**Comment by rmhrisk** [comment]
Let's skip Microsoft for now.

**Comment by fotisl** [comment]
@YuryStrozhevsky Just execute 'expand' and let me know if the command exists.

**Comment by YuryStrozhevsky** [comment]
@fotisl Yes, it does exist.

**Comment by fotisl** [comment]
I will have a look into it.

**Comment by YuryStrozhevsky** [comment]
Made a fix, now all works fine, closing.

**Comment by fotisl** [comment]
I would like to mention that this only fixes the issue with the EU TSL download, the expand issue is for the Microsoft TL download. I am monitoring the website which sends the problematic chain, when they fix it the patch should be reverted for security reasons.

**Comment by YuryStrozhevsky** [comment]
In fact in Chrome the “bad link” shows as having 100% correct certificate. So, most probably the problem is not on the bad site, but in internal Node TLS implementation. I had no time to digg deeper.

**Comment by fotisl** [comment]
The problem is that the chain sent is incorrect. If you have the correct Sub cached in your browser it will work correctly. It is not a node problem.

**Comment by YuryStrozhevsky** [comment]
Ok, tomorrow I will spend some time checking it, I promise.

**Comment by YuryStrozhevsky** [comment]
@fotisl So, I checked the certificates the server sends. In fact it is the first time I seen certificates using "Signed Certificate Timestamp" extension (RFC6962). I am not an expert in TLS, but as soon the certs were recognized in Chrome and they do use Certificate Transparency system I think these certs are correct. And I still think there is a problem in Node.js TLS implementation, probably Node.js does not fully support verification of certificates using Certificate Transparency.

**Comment by YuryStrozhevsky** [comment]
@fotisl You could use [this link](https://cryptoreport.websecurity.symantec.com/checker/views/ctsearch.jsp) to check "the bad site" for Certificate Transparency support. Just put "www.eett.gr" and press "Search Logs".
