### ISSUE TITLE
Microsoft SERVER_AUTH fetch returned an EV Code Signing OID

### ISSUE THREAD

**Issue by konklone** [PeculiarVentures/tl-create#70]
The `evpolicy` field for at least one of the certificates fetched when running:

```bash
node ./src/bin/tl-create.js --mozilla --microsoft --apple roots.js --for SERVER_AUTH --format js
```

Contains `2.23.140.1.3`, which is the [EV Code Signing OID](https://cabforum.org/object-registry/).

The files uploaded to #68 can be used to see the raw results.

**Comment by fotisl** [comment]
There are 4 different CAs that return the CA/B Forum EV CS OID. However, all of them are also used for SERVER_AUTH and in the list of EV OIDs they contain the TLS OIDs too (2.23.140.1.1 or an OID under the CA's arc). I believe that the output is correct.
