### ISSUE TITLE
Unable to generate Mozilla TL

### ISSUE THREAD

**Issue by WorldThirteen** [PeculiarVentures/tl-create#73]
#### Got the next output:
```
Parsing started: 2019:12:21:00:45:25
Trust Lists: Mozilla
Error: Can not parse row 168: CKA_NSS_SERVER_DISTRUST_AFTER CK_BBOOL CK_FALSE
Cannot fetch any Trust Lists.
```

#### Source of issue:
-> Mozilla Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1465613,
-> Implementation: https://hg.mozilla.org/projects/nss/rev/52024949df95c7147c4995bb8ddc094027636001

Mozilla has added two new fields for builtins certificates:
`CKA_NSS_SERVER_DISTRUST_AFTER`
`CKA_NSS_EMAIL_DISTRUST_AFTER`
#### Solution:
Add these fields to map of known Mozilla attributes.

**Comment by rmhrisk** [comment]
Please fix
