### ISSUE TITLE
Need to use EUTL as a list of TL, retrieve each and parse

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/tl-create#8]
Right now tl-create processes only the primary EUTL and not the referenced children. This is a problem because the per-country TL are the ones that contain the actual CAs to trust. 

**Notes** 
- The primary EUTL is a list of TL. Each TL needs to be fetched and processed.
- The certificates in the main EUTL are used as potential signers of the child TLs.
- We need to extract all the CA certificates from the child TLs. We can add signature verification in later.

**Comment by as-if-ur** [comment]
Solved
